-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "orderDate" TYPE TIMESTAMPTZ USING "orderDate" AT TIME ZONE 'UTC';
ALTER TABLE "Payment" ALTER COLUMN "processedAt" TYPE TIMESTAMPTZ USING "processedAt" AT TIME ZONE 'UTC';
